#!/usr/bin/env bash
# Every tool directory must expose a complete lifecycle handler set:
# install_*, uninstall_*, update_* (reinstall_* is generated by
# _register_safe_reinstall_handlers). The dispatcher normalises "-" to "_"
# before looking the handler up, so a handler declared with a hyphen (or a
# truncated name) is invisible and the tool can never be installed.
set -uo pipefail

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$ROOT_DIR"

pass=0
failed=0

run_test() {
  local name="$1"
  shift
    local rc=0 errexit_was_on=0
  [[ $- == *e* ]] && errexit_was_on=1
  set +e
  ( set -e; "$@" )
  rc=$?
  if (( errexit_was_on )); then set -e; fi
  if (( rc == 0 )); then
    ((pass += 1))
    printf 'ok - %s\n' "$name"
  else
    ((failed += 1))
    printf 'not ok - %s\n' "$name" >&2
  fi
}

check_module_handlers() (
  local module="$1"
  local tools_dir="$ROOT_DIR/karnel/tools/$module"
  [[ -d "$tools_dir" ]] || exit 0
  [[ -f "$tools_dir/all.sh" ]] || exit 0

  export KARNEL_PATH="$ROOT_DIR/karnel"
  export KARNEL_READ_ONLY=1
  export PREFIX="${PREFIX:-/data/data/com.termux/files/usr}"
  export KARNEL_CACHE="${TMPDIR:-/tmp}/karnel-handler-test/cache"
  export KARNEL_DATA="${TMPDIR:-/tmp}/karnel-handler-test/data"
  export KARNEL_CONFIG="${TMPDIR:-/tmp}/karnel-handler-test/config"
  export HOME="${HOME:-/data/data/com.termux/files/home}"
  mkdir -p "$KARNEL_CACHE" "$KARNEL_DATA" "$KARNEL_CONFIG"

  source "$KARNEL_PATH/utils/bootstrap.sh"
  import "@/utils/env" || exit 1
  import "@/utils/log" || exit 1
  import "@/utils/colors" || exit 1
  import "@/utils/install" || exit 1
  import "@/utils/tools" || exit 1

  import "@/tools/$module/all" || exit 1

  local dir tool normalized missing=()
  for dir in "$tools_dir"/*/; do
    [[ -d "$dir" ]] || continue
    [[ -f "$dir/install.sh" ]] || continue
    tool="$(basename "$dir")"
    normalized="${tool//-/_}"
    for action in install uninstall update; do
      if ! declare -f "${action}_${normalized}" >/dev/null; then
        missing+=("$tool:${action}_${normalized}")
      fi
    done
  done

  if ((${#missing[@]} > 0)); then
    printf 'missing handlers in %s:\n' "$module" >&2
    printf '  %s\n' "${missing[@]}" >&2
    exit 1
  fi
  exit 0
)

for module_dir in "$ROOT_DIR"/karnel/tools/*/; do
  module="$(basename "$module_dir")"
  [[ -f "$module_dir/all.sh" ]] || continue
  run_test "lifecycle handlers exist for module $module" check_module_handlers "$module"
done

echo
echo "installer-handlers: $pass passed, $failed failed"
((failed == 0))
